trigger:
- main

variables:
  imageName: flask-aks-app
  acrName: prashantacrdevops01

stages:

# =========================
# TERRAFORM STAGE
# =========================
- stage: Terraform
  displayName: Terraform Infra Provision
  jobs:
  - job: Terraform
    pool:
      vmImage: ubuntu-latest
    steps:

    # ✅ Install Terraform
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: '1.6.6'

    # ✅ Terraform Init
    - task: TerraformTaskV4@4
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: 'terraform/envs/dev'   # 🔥 IMPORTANT
        backendServiceArm: 'azure-connection'
        backendAzureRmResourceGroupName: 'rg-devops-project'
        backendAzureRmStorageAccountName: 'tfstateprashant123'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'terraform.tfstate'

    # ✅ Terraform Apply
    - task: TerraformTaskV4@4
      displayName: Terraform Apply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: 'terraform/envs/dev'   # 🔥 IMPORTANT
        environmentServiceNameAzureRM: 'azure-connection'
        commandOptions: '-auto-approve'

# =========================
# BUILD STAGE
# =========================
- stage: Build
  displayName: Build and Push Image
  dependsOn: Terraform
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: Docker@2
      displayName: Build and Push to ACR
      inputs:
        containerRegistry: 'acr-connection'
        repository: 'flask-aks-app'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          v1

# =========================
# DEPLOY STAGE
# =========================
- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: Build
  jobs:
  - job: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: Kubernetes@1
      displayName: Deploy to AKS
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'aks-connection'
        namespace: 'default'
        command: apply
        useConfigurationFile: true
        configuration: k8s/deployment.yaml
