trigger:
- main

variables:
  imageName: flask-aks-app
  acrName: prashantacrdevops01

stages:

# =========================
# TERRAFORM STAGE
# =========================
- stage: Terraform
  displayName: Terraform Infra Provision
  jobs:
  - job: Terraform
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: AzureCLI@2
      displayName: Terraform Init & Apply
      inputs:
        azureSubscription: 'azure-connection'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          cd terraform/envs/dev
          terraform init
          terraform apply -auto-approve

# =========================
# BUILD STAGE
# =========================
- stage: Build
  dependsOn: Terraform
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: Docker@2
      inputs:
        containerRegistry: 'acr-connection'
        repository: 'flask-aks-app'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          v1

# =========================
# DEPLOY STAGE
# =========================
- stage: Deploy
  dependsOn: Build
  jobs:
  - job: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'aks-connection'
        namespace: 'default'
        command: apply
        useConfigurationFile: true
        configuration: k8s/deployment.yaml
